version: "3"

services:
  postgres:
    image: postgres:10
    logging:
      driver: json-file
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    logging:
      driver: json-file
    build:
      context: .
      args:
        - cachet_ver=2.4
    ports:
      - 49888:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - DEBUG=false
    depends_on:
      - postgres
    restart: on-failure
